Support simulated time
wentasah/r2r pull request #1
Opened 2023-11-15 14:15 UTC by skoudmar

Simulated time can be enabled:

- Implicitly, by registering a parameter handler. While launching the node, parameter `use_sim_time` must be set to `true`.
- Explicitly, by calling `TimeSource::enable_sim_time(&self)`.

It works but needs more polishing.

2023-12-12 16:41 UTC, wentasah requested changes
I went through it. It works, but I have a few comments and change requests. Most of them are related to making it easier to undertand the code (and commit messages).

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
> +use std::pin::Pin;
This related to the commit message:
> During the initialization of timer with RosTime clock the timer adds jump callback with rcl_jump_callback_info_t to the clock with .user_data being the address of the timer handle.

This is not clear? Which initialization do you mean? In r2r or in rcl? Where is the "jump callback" (btw what it is?) added? Name the exact function or method you are talking about. "To the clock with ..." - again - be specific. Do you mean some specific data structure? Name it exactly.

Also write in which function would the segfault happen.

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
> +    }
This is confusing. It seems you are adding this code, but you are actually changing some part of it. The previous version is two pages below so it took me non-trivial amount of time to figure out what was actually changes and why.

It seems that this is just due to making the `_clock` Optional. Please make this change to `Optional<Clock>` a separate commit. This will make reading this commit much easier.

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
> +    _clock: Option<Clock>, // Some(clock) if the timer owns the clock, just here to be dropped properly later.
As noted above, make this separate commit (before this one).

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
> +    // shared ros clock
Shared between what? Perhaps change to "RosTime clock used by all timers created by create_timer()

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
>      timers: Vec<Timer_>,
I thing the commit message can start like this:

> Allow creating timers of type ClockType::RosTime
> 
> This adds Node::create_timer() method. The method is similar to
> already existing Node::create_wall_timer(), but the timer is based on
> ClockType::RosTime rahter than on ClockType::SteadyTime.
> 
> The advantage of ClockType::RosTime is that one can drive the clock
> from a different time source. This will be used in the next commits to
> implement for clock source on the /clock topic.
>

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
> +    // time source that provides simulated time
```suggestion
    // time source that provides time from the /clock topic
```

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
> +    }
These public functions should be documented.

2023-12-12 16:41 UTC, wentasah commented on r2r/src/nodes.rs
> +    pub fn now(&self) -> Result<Duration> {
This function doesn't seem to be used anywhere. Use it at least in some example (and document it) or remove it.

2023-12-12 16:41 UTC, wentasah commented on r2r/Cargo.toml
>  [features]
Commit message:

You should first say what you are doing here and only then mention that it's feature-gated and why.

As far as I can see you are:
1. Adding TimeSource type. Mention that is related (or implements the same thing) as some rclcpp type.
2. Adding `Clock` methods `*_time_override`. Again, mention what are their rclcpp equivalents.
3. Initializing TimeSource in every node.
4. Enabling the simulated time if Node parameter `use_sim_time` is true.
5. Adding some `Node` methods.

It is a question, whether we need all these changes in a single commit. If this would be split to smaller pieces, it would be easier to figure out which change is relate to which of the above 5 points.

2023-12-12 16:41 UTC, wentasah commented on r2r/examples/sim_time_publisher.rs
> +        println!("Publishing time {:3} s {:9} ns", time.as_secs(), time.subsec_nanos());
```suggestion
        println!("Publishing time {}.{:9} s", time.as_secs(), time.subsec_nanos());
```

2023-12-12 16:41 UTC, wentasah commented on r2r/src/clocks.rs
> +    pub(crate) fn disable_ros_time_override(&mut self) -> Result<()> {
When compiling without `sim-time` feature, I get a lot of  **never used** warnings, such as:

    warning: methods `disable_ros_time_override` and `set_ros_time_override` are never used

2023-12-12 16:41 UTC, wentasah commented on r2r/examples/timer_sim_time.rs
> +            "\tcurrent time ros={}s, system={}s",
```suggestion
            "\tcurrent time ros={:.3}s, system={:.3}s",
```

2023-12-12 16:41 UTC, wentasah commented on r2r/examples/timer_sim_time.rs
> +    time_source.enable_sim_time(&mut node)?;
When I try commenting this line and running the example as:

    cargo run --features=sim-time --example=timer_sim_time -- --ros-args -p use_sim_time:=true
    
sim time is not enabled.

I would prefer not having this line here and having a comment in the source code about how to run it with sim time enabled. Perhaps, if the sim time is not enabled, the example could print how to enable it to stdout.

2023-12-12 16:41 UTC, wentasah commented on r2r/examples/timer_sim_time.rs
> +    let mut x: i32 = 0;
Rename `x` to something more descriptive. For example `iteration`.

2023-12-12 16:41 UTC, wentasah commented on r2r/examples/timer_sim_time.rs
> +use futures::executor::LocalPool;
Add a comment how to run this example. See below and also mention that the functionality can be demonstrated together with `sim_time_publisher` (or with `ros2 bag play --clock` )

2023-12-12 16:41 UTC, wentasah commented on r2r/src/time_source.rs
> +    /// If the simulated time is enabled the [TimeSource] will distribute simulated time
... enabled by calling `enable_sim_time()` ...

2023-12-12 16:41 UTC, wentasah commented on r2r/src/time_source.rs
Document also the `TimeSource` struct - at least one sentence. Currently the documentation looks like this:

![image](https://github.com/wentasah/r2r/assets/140542/d00dfc9d-510b-4c3f-a208-f70418ee452b)

2023-12-12 16:41 UTC, wentasah commented on r2r/src/time_source.rs
> +    ///  topic in the next call to [Node::spin_once].
You document that happens if `remove_subscriber` is true. But what happens if it's false? Does it have some consequences? Why it is useful to have this parameter at all?

2023-12-12 16:41 UTC, wentasah commented on r2r/src/time_source.rs
> +    /// Attach clock of type [RosTime](ClockType::RosTime) to the [TimeSource]
In general, the documentation should be the part of the commit, which adds the code. It would make the review much easier.

2024-03-16 08:12 UTC, wentasah commented
Narazili jsme na problém, že když `/clock` poskočí o víc než je 2x perioda timeru, tak se timer callback vyvolá jen jednou a ne víckrát, jak bych očekával. Můžeš zjistit, jestli je to chyba v této implementaci, nebo jestli se `rclcpp` chová stejně?

2024-03-16 18:21 UTC, skoudmar commented
Takhle je to implementováno už v `rcl` a `rclcpp` chování nijak nemění.

Při každé změně času se timer callback zavolá nejvýše jednou.

2025-03-05 10:29 UTC, closed without merging